[project]
name = "DataNest"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.access-control]
path = "contracts/access-control.clar"
depends_on = []

[contracts.payment]
path = "contracts/payment.clar"
depends_on = []

[contracts.storage]
path = "contracts/storage.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
